version: "3.4"

services:
  conductor:
    image: "simwilso/ledger:0.2"
    network_mode: host
    volumes:
      - type: volume
        source: ledgerdata3
        target: /tem/databases
    environment:
      APPLICATION_ID: "edge-1"
      PORT: 8890
      HC_PORT: 9992

volumes:
  ledgerdata3:
