version: "3.4"

services:
  cloud:
    image: "simwilso/ledger:0.2"
    network_mode: host
    volumes:
      - type: volume
        source: ledgerdata1
        target: /tem/databases
    environment:
      APPLICATION_ID: cloud
      IS_CLOUD: "true"
      PORT: 8888

  edge0:
    image: "simwilso/ledger:0.2"
    network_mode: host
    volumes:
      - type: volume
        source: ledgerdata2
        target: /tem/databases
    environment:
      APPLICATION_ID: "edge-0"
      PORT: 8889
      HC_PORT: 9991

  edge1:
    image: "simwilso/ledger:0.2"
    network_mode: host
    volumes:
      - type: volume
        source: ledgerdata3
        target: /tem/databases
    environment:
      APPLICATION_ID: "edge-0"
      PORT: 8890
      HC_PORT: 9992

volumes:
  ledgerdata1:
  ledgerdata2:
  ledgerdata3:
