version: "3.4"

services:
  conductor:
    image: "simwilso/ledger:0.2"
    network_mode: host
    volumes:
      - type: volume
        source: ledgerdata1
        target: /tem/databases
    environment:
      APPLICATION_ID: cloud
      IS_CLOUD: "true"
      PORT: 8888
      DEBUG: "debug"

volumes:
  ledgerdata1:
