[package]
authors = ["redgridone"]
edition = "2018"
name = "tem"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "tem"

[dependencies]
derive_more = "0"
serde = "1"
chrono = {version = "0.4", features = ["serde"]}
hdk = "0.0.121"
holo_hash = "0.0.10"
