name: Solution Tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-and-test:
    # Name the Job
    name: Build and Test TEM
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell . --run "cd tem/express-relayer && npm install"
      - run: nix-shell . --run "cd tem/tests && npm install"
      - run: nix-shell . --run "cd tem/tests && npm test && npm run test:messages"
